stages:
  - release

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  variables:
    GORELEASER_IMAGE: mailchain/goreleaser-xcgo:latest
    GITLAB_USER: cquintana92
    GITLAB_PROJECT: shoppinglist-server
    GIT_DEPTH: 0
  only:
    refs:
      - tags
  script: |

    apk add --update --no-cache gcc sqlite
    docker pull $GORELEASER_IMAGE

    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/$GITLAB_USER/$GITLAB_PROJECT \
      -w /go/src/gitlab.com/$GITLAB_USER/$GITLAB_PROJECT \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e GITLAB_TOKEN \
      $GORELEASER_IMAGE release --rm-dist

release:docker:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  only:
    refs:
      - tags
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - echo "CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}"
    - CI_COMMIT_REF_NAME=`echo "${CI_COMMIT_REF_NAME}" | sed 's:/:-:g'`
    - echo "CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}"
    - IMAGE_NAME="cquintana92/shoppinglist:${CI_COMMIT_REF_NAME}"
    - LATEST_IMAGE_NAME="cquintana92/shoppinglist:latest"
    - echo "IMAGE_NAME=${IMAGE_NAME}"
    - docker build . -t "${IMAGE_NAME}"
    - docker push "${IMAGE_NAME}"
    - docker tag "${IMAGE_NAME}" "${LATEST_IMAGE_NAME}"
    - docker push "${LATEST_IMAGE_NAME}"

