project_name: shoppinglist-server
before:
  hooks:
    - go mod download
builds:
  - id: main
    binary: server
    main: ./cmd/server/main.go
    ldflags:
      - -X "constants.VERSION={{.Version}}"
    targets:
      - "darwin_amd64"
      - "linux_amd64"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

