version: '3'
services:
  postgresql:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppinglist
    ports:
      - "5432:5432"
