name: Docker image
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  REPOSITORY: cquintana92/shoppinglist-server

jobs:
  # Generate docker image
  docker:
    name: docker-image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the release version from the tag
        if: env.BIN_VERSION == ''
        run: |
          # Apparently, this is the right way to get a tag name. Really?
          #
          # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
          echo "BIN_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.BIN_VERSION }}"

      - name: Create docker image
        run: |
          docker build . -t "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.BIN_VERSION }}"
          docker tag "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.BIN_VERSION }}" "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest"

      - name: Upload docker image
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.BIN_VERSION }}"
          docker push "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest"

      - name: Log in to the Public Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push image to docker registry
        run: |
          docker tag "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest" "docker.io/${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:${{ env.BIN_VERSION }}"
          docker tag "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest" "docker.io/${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:latest"
          docker push "docker.io/${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:${{ env.BIN_VERSION }}"
          docker push "docker.io/${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ secrets.DOCKER_REGISTRY_REPOSITORY }}:latest"


