name: test
on:
  pull_request: {}
  push:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      # Setup repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      # Check format
      - run: make test

